#!/bin/bash --login

#PBS -l nodes=1:ppn=1
#PBS -l walltime=08:00:00
#PBS -l mem=700gb

#PBS -j oe /mnt/scratch/${USER}/MG-RAST_samples
#PBS -M youremail@email.com
#PBS -m abe
#PBS -N IowaCorn_qcQuality

### switch into the correct scratch directory
cd /mnt/scratch/${USER}/MG-RAST_samples

### load fastx
module load FASTX/0.0.14

### get quality stats for the quality-trimmed data of IowaCorn

### Iowa_agricultural_4509400.3.qc.fastq.gz:
fastx_quality_stats -i Iowa_agricultural_4509400.3.qc.fastq.gz -o Iowa_agricultural_4509400.3_qc_quality.txt

### Iowa_agricultural_4509401.3.qc.fastq.gz:
fastx_quality_stats -i Iowa_agricultural_4509401.3.qc.fastq.gz -o Iowa_agricultural_4509401.3_qc_quality.txt
