#!/bin/bash --login

#PBS -l nodes=1:ppn=1
#PBS -l walltime=16:00:00
#PBS -l mem=500gb

#PBS -j oe
#PBS -M my_email
#PBS -m abe
#PBS -N IowaAgCensus

### myPy2 is what I named my Python virtualenv
cd /mnt/research/ShadeLab/WorkingSpace/Yeh/myPy2/bin

module load NumPy
module load SciPy
module load Biopython
source /mnt/research/ShadeLab/WorkingSpace/Yeh/myPy2/bin/activate

python run_microbe_census.py /my-directory/Iowa_agricultural_4509400.3.qc.fastq.gz Iowa_agricultural_4509400.3_census

python run_microbe_census.py /my-directory/Iowa_agricultural_4509401.3.qc.fastq.gz Iowa_agricultural_4509401.3_census
